version: '2'

services:
  app:
    build:
      context: app
    container_name: app
    ports:
      - "5000:5000"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - "app"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboard.yml
    ports:
      - "3000:3000"
    depends_on:
      - "prometheus"