version: '2'

services:
  app:
    build:
      context: app
    container_name: app
    ports:
      - "5000:5000"

  prometheus:
    build:
      context: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - "app"

  grafana:
    build:
      context: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - "prometheus"